### ISSUE TITLE
Comodo took over vFense?

### ISSUE THREAD

**Issue by jrosetto** [vFense/vFense#223]
Looks like Comodo took the vFense code and fixed the remaining issues with it and are offering a free service with it now.  No more delays in the web interface, no compiling windows agents.

[https://one.comodo.com/](https://one.comodo.com/)

**Comment by theangryangel** [comment]
Brought this up back in https://github.com/vFense/vFense/issues/206#issuecomment-140760930 

The devs werent aware that the time, and frankly the interactions I've had with Comodo since over the One platform, I wouldn't touch them with a barge pole.

**Comment by jrosetto** [comment]
vFense is so close to being done I wish someone could spend some quality time with it to finish it.  Come on people :p.

**Comment by jrosetto** [comment]
What exactly is your issue with comodo out of interest?

**Comment by theangryangel** [comment]
I signed up for Comodo One to try it out around when I posted that comment. At that time the platform was not exactly stable, and was very clearly a collection of open source tools very badly cobbled together. Whilst they are completely in their right to do that, I was bit surprised that they weren't financially or otherwise providing support to this project.

Since I signed up to test Comodo One I've been harassed twice by different sales managers, over the period of weeks. Both instances I seem to have been assigned a new "account manager" which triggered this. Both refused to take no for an answer, insisted on calling back, emailing, etc. On the last time I answered the phone where I tried to expand on my "No, I'm really not interested, please stop wasting my time. I have another product." I was conferenced on with other people before I realised what was happening and it felt like they just wanted me to submit through fatigue. 

Between what I feel like is the worse sales technique I have ever encountered, and things like [Comodo's Lets Encrypt trademark attempt](https://letsencrypt.org/2016/06/23/defending-our-brand.html), [their AV issues](https://bugs.chromium.org/p/project-zero/issues/list?can=1&q=comodo&colspec=ID+Type+Status+Priority+Milestone+Owner+Summary&cells=ids), I really just want nothing to do with them at all.

**Comment by jrosetto** [comment]
I'm in the same boat right now.  They keep calling over and over even though I told them I wasn't interested.

**Comment by jlk** [comment]
I'm curious - what's the issue here you folks would like to see fixed, or is this just an issue created to get things off your chest? If you have issues, are they clearly created in other issues for people to address?

This is an open source project. There's no stopping Comodo or somebody else from forking the code and doing as they wish with it, within the GPL license under which this software is licensed. Making noise about it on social media might provide encouragement to contribute the changes back - I'll try that myself. 

As much as I hate it when people say it to me, pull requests would happily be accepted by Allen. It'd be great to get some active developers on this project, but you have to understand that people go in different directions in life and might not have time to work on something anymore. I'd love to put in a few weeks work on this project, but I know the chance of that happening this year is close to zero. Just asking that you keep this in mind.

**Comment by jrosetto** [comment]
When a client checks in the vfense web interface can take hours upon hours to reflect the new machine.  I'm not looking for a complete list of updates for the machine, just that the machine show up so I know that the installation was successful and it is communicating with vFense.  I also have the same issue when adding a customer in the web interface and it can take hours to show up.  If that was fixed vFense would be basically production ready.

**Comment by jrosetto** [comment]
OK I think I found the issue.  The agents and everything show up basically instantly.  It is a caching issue with the browser.  If I reset internet explorer, close, log back in the information is there.  Do we just need some code to not cache the page?
